### ISSUE TITLE
Question about LPIPS percentage point metric

### ISSUE THREAD

**Issue by yjhong89** [isl-org/StableViewSynthesis#20]
Dear author, 

I have read "Stable View Synthesis" and wonders what is LPIP pertancage point metric.

In general, LPIPS measures the perceptual distance in Euclidean and even your another paper "Free View Synthesis" report LPIPS, not LPIPS percentage point.

Can you explain how LPIPS percentage point is calculated ?
And if LPIPS percentage point is relative to the best prior state of the art, why lower LPIPS percentage point is better than higher ?

Thank you for your great work!

Best regards,
YJHong.

**Comment by griegler** [comment]
LPIPS% = 100 * LPIPS. 
As you have written, LPIPS is a Euclidean distance in feature space, hence, lower is better.

**Comment by yjhong89** [comment]
@griegler 
Thank you!
Close the issue.
